// Generated by delombok at Wed May 06 15:55:13 CST 2020

public class Main {
    public static void main(String[] args) {
        System.out.println(1);
        a aa = new a();
        aa.setC(0);
        System.out.println(aa);
    }
}

class a {
    int c;

    @java.lang.SuppressWarnings("all")
    public a() {
    }

    @java.lang.SuppressWarnings("all")
    public int getC() {
        return this.c;
    }

    @java.lang.SuppressWarnings("all")
    public void setC(final int c) {
        this.c = c;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof a)) return false;
        final a other = (a) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getC() != other.getC()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof a;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getC();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "a(c=" + this.getC() + ")";
    }
}
